services:
  redis:
    container_name: redis1
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - gdg_network
      -

  mongodb:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    networks:
      - gdg_network
    volumes:
      - mongodb_data:/data/db

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8080"
    environment:
      - MYSQL_USER=${PROD_DB_USERNAME}
      - MYSQL_PASSWORD=${PROD_DB_PASSWORD}
      - MYSQL_URL=jdbc:mysql://${PROD_DB_ENDPOINT}:3306/${PROD_DB_NAME}?serverTimezone=UTC
    networks:
      - gdg_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api.zimeet.store:/etc/letsencrypt/live/api.zimeet.store:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - gdg_network
    restart: always

networks:
  gdg_network:
    driver: bridge