DROP TABLE IF EXISTS user_terms;
DROP TABLE IF EXISTS terms;

ALTER TABLE team
    MODIFY COLUMN verification ENUM('COMPLETE', 'NONE') DEFAULT 'NONE' NOT NULL;

ALTER TABLE user_profile
    MODIFY COLUMN level ENUM('LIGHT', 'PLUS') NOT NULL DEFAULT 'LIGHT';
