ALTER TABLE team
    ADD COLUMN active_status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN event ENUM('AU_2025', 'DA_2025', 'NEUL_2025') NOT NULL DEFAULT 'AU_2025';


ALTER TABLE hi
    MODIFY COLUMN hi_status ENUM('ACCEPT', 'EXPIRED', 'NONE', 'REFUSE', 'DELETED') NOT NULL;
